# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{songkickr}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jared Mehle"]
  s.date = %q{2010-05-03}
  s.description = %q{A Ruby wrapper around the Songkick API. Visit www.songkick.com/developer for documentation on the Songkick API. }
  s.email = %q{jrmehle@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/songkickr.rb",
     "lib/songkickr/artist.rb",
     "lib/songkickr/concert_setlist_result.rb",
     "lib/songkickr/event.rb",
     "lib/songkickr/event_result.rb",
     "lib/songkickr/location.rb",
     "lib/songkickr/performance.rb",
     "lib/songkickr/remote.rb",
     "lib/songkickr/setlist.rb",
     "lib/songkickr/setlist_item.rb",
     "lib/songkickr/venue.rb",
     "songkickr.gemspec",
     "test/fixtures/events.json",
     "test/fixtures/no_events.json",
     "test/helper.rb",
     "test/songkickr/test_artist.rb",
     "test/songkickr/test_remote.rb",
     "test/test_songkickr.rb"
  ]
  s.homepage = %q{http://github.com/jrmehle/songkickr}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A Ruby wrapper around the Songkick API.}
  s.test_files = [
    "test/helper.rb",
     "test/songkickr/test_artist.rb",
     "test/songkickr/test_remote.rb",
     "test/test_songkickr.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

